services:
  - type: web
    name: hound-forward-web
    env: docker
    plan: starter
    rootDir: web
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: REDIS_URL
        fromService:
          name: hound-forward-redis
          type: redis
          property: connectionString

  - type: worker
    name: hound-forward-worker
    env: docker
    plan: standard
    rootDir: worker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: REDIS_URL
        fromService:
          name: hound-forward-redis
          type: redis
          property: connectionString
      - key: USE_DLC
        value: "True"

  - type: redis
    name: hound-forward-redis
    ipAllowList: []
